project:
  type: website
  output-dir: docs

website:
  title: "Bioestad√≠stica"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Sesion1_lect.Rmd
      - Sesion2_lect.Rmd
      - Sesion3_lect.Rmd
      - Sesion4_lect.Rmd
      - Sesion5_lect.Rmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: source

